name: Build and test project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install Requirements
        run: npm install
      - name: Build
        run: npm run build
      - name: Check Format
        run: npm run format:check
      - name: Lint
        run: npm run lint:check
      - name: Test
        run: npm run test
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
      - name: Archive Verified Build
        uses: actions/upload-artifact@v4
        with:
          name: dist-verified
          path: |
            main.js
            manifest.json
            styles.css
