name: Build and Test Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  NODE_VERSION: "22"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build, Test, and Coverage
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build
      - name: Run Tests
        run: npm run test
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload Test Results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Save Build Output
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          retention-days: 7
          path: |
            main.js
            manifest.json
            styles.css
