name: Auto-update Pre-commit Hooks

on:
  schedule:
    - cron: "0 8 1 * *" # Run at 08:00 UTC on the 1st of every month
  workflow_dispatch:

jobs:
  update-precommit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Auto Update Pre-Commit Action
        uses: LeonLuttenberger/gh-auto-update-precommit@v1.0.1
